app:
  base-url: http://localhost:${server.port:8080}

jwt:
  secret: giannis

encryption:
  private:
    key: 234342

spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  resources.cache.cachecontrol.max-age: 86400 # 1d
  servlet.multipart:
    max-file-size: 2MB
    max-request-size: 3MB
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  output.ansi.enabled: ALWAYS
  flyway:
    locations:
      - classpath:db.migration
      - filesystem:./sql

